module.exports = {
  any: require('./any'),
  concat: require('./concat'),
  every: require('./every'),
  filter: require('./filter'),
  find: require('./find'),
  first: require('./first'),
  firstRest: require('./firstRest'),
  flatMap: require('./flatMap'),
  flatten: require('./flatten'),
  forEach: require('./forEach'),
  hasKey: require('./hasKey'),
  last: require('./last'),
  map: require('./map'),
  mapFilter: require('./mapFilter'),
  reduce: require('./reduce'),
  rest: require('./rest'),
  reverse: require('./reverse'),
  size: require('./size'),
  sort: require('./sort'),
  splitWhen: require('./splitWhen'),
  takeUntil: require('./takeUntil'),
  takeWhile: require('./takeWhile'),
  truncate: require('./truncate'),
  truncateLast: require('./truncateLast')
};
